### ISSUE TITLE
Metamask Alerts 

### ISSUE THREAD

**Issue by patrykadas** [Userfeeds/cryptopurr#1]
![metamask alerts](https://user-images.githubusercontent.com/6234032/38499739-d00a26da-3c08-11e8-9481-8654747cadee.png)

**Comment by michalwarda** [comment]
@patrykadas can you upload svg icons for this?

**Comment by patrykadas** [comment]
@michalwarda 
[icons.zip](https://github.com/Userfeeds/cryptopurr/files/1891156/icons.zip)

**Comment by michalwarda** [comment]
I've simplified the design a bit with removing the circles and badge wrappers. I'll close this for now.
