### ISSUE TITLE
Should display the whole text sent to blockchain.

### ISSUE THREAD

**Issue by mg6maciej** [Userfeeds/cryptopurr#18]
<img width="747" alt="image" src="https://user-images.githubusercontent.com/1316369/38719764-ef2ad238-3ef3-11e8-89a7-7701f5c72734.png">

**Comment by michalwarda** [comment]
@mg6maciej can you say what you think should've shown?

**Comment by mg6maciej** [comment]
interface TheUniversalApi { @GET fun get(@Url url: String): Single<Map<String, Any>> }

**Comment by michalwarda** [comment]
Done!
