### ISSUE TITLE
Promoting Kitty avatars on home page

### ISSUE THREAD

**Issue by gkapkowski** [Userfeeds/cryptopurr#25]
THE-SIMPLEST-THING-EVER

The idea: we need to provide `boxed` monetization scheme for developers that fork cryptopurr interface. They need to have ability to start earning eth from day 1 after forking.

Add ability to `Boost` kitty avatar (not post or anything else, only avatars)
This will show it at CryptoPurr home page at the top. 
The button to promote given cat should be visible on cats profile.

Something with this structure:
![promoted](https://user-images.githubusercontent.com/114996/38935765-7588d328-431f-11e8-95bd-22f6f01e47d7.png)
(^^ Patryk Help!)

**Comment by mg6maciej** [comment]
API: https://api-staging.userfeeds.io/ranking/experimental_boost;asset=ethereum;context=0xInterfaceOwnerEthereumAddress

    {
        "items": [
            {
                "id": {identifier of kitty on cryptopurr},
                "score": 10000000000
            }
        ]
    }

Suggested identifers (choose best):

* `https://userfeeds.github.io/cryptopurr/608827` (relevant for the whole platform, might get out of date, harder to parse, but can redirect using this link directly to profile)
* `cryptopurr.co:608827` or `cryptopurr:608827` (easy to parse, still possible to find the meaning outsite of this app context)
* `608827` (easiest to handle for this app developer)
* `ethereum:0x06012c8cf97bead5deae237070f9587f8e7a266d:608827` (already has meaning inside the platform, claim with such data can have a different meaning in other contexts, i.e. "follow")

Claim structure:

    {
        "claim": {
            "target": {identifier of kitty on cryptopurr}
        }
    }

Contract (mainnet):
0x70B610F7072E742d4278eC55C02426Dbaaee388C

ABI:
```
[
	{
		"constant": false,
		"inputs": [
			{
				"name": "userfeed",
				"type": "address"
			},
			{
				"name": "data",
				"type": "string"
			}
		],
		"name": "post",
		"outputs": [],
		"payable": true,
		"stateMutability": "payable",
		"type": "function"
	}
]
```

Send claim with predefined value (e.g. 0.001 ETH) or allow a few different values (0.001, 0.01, 0.1 ETH)

**Comment by mg6maciej** [comment]
@patrykadas Design?

Suggestion: only show top 6 profiles, because 6 is such a perfect number.

**Comment by patrykadas** [comment]
1. On the main feed I'd just include section like this with three kittens:
![1](https://user-images.githubusercontent.com/6234032/39307575-85db040e-4963-11e8-8fc0-8602c75138dc.png)
**In the future I'd like to expand this tile with information about current state of kittie (siring / for sale)**
2. Boosting:
![2](https://user-images.githubusercontent.com/6234032/39307576-86032bd2-4963-11e8-9c9a-bed3b79613f6.png)
3. After clicking 'show more' we go to /leaderboard:
![3](https://user-images.githubusercontent.com/6234032/39307577-861fc63e-4963-11e8-9efa-9951a2cf3387.png)
4. And button on kitten's profile
<img width="839" alt="screen shot 2018-04-26 at 15 06 42" src="https://user-images.githubusercontent.com/6234032/39307581-89c88fa0-4963-11e8-9355-52e26b7dcbf2.png">

**Comment by gkapkowski** [comment]
@patrykadas 

The `Purrmoted` should be above `Purr your story`. To not split the experience of posting/reading.
Can we do `smaller` avatars that expand on mouse `hover`? I don't want this to take so much space by default.

:+1: for adding additional information later.

Side note: We can use this as use case for creation of universal boost button, that can be quickly added to any website.

**Comment by patrykadas** [comment]
![featured-mobile](https://user-images.githubusercontent.com/6234032/39810780-a8abb870-5386-11e8-837f-a8193a723678.png)
![featured](https://user-images.githubusercontent.com/6234032/39810781-a8ee54d2-5386-11e8-94c8-272ced2e0b66.png)
![leaderboard-mobile](https://user-images.githubusercontent.com/6234032/39810782-a90d2f10-5386-11e8-99b9-d0a75f8ffead.png)
![leaderboard](https://user-images.githubusercontent.com/6234032/39810783-a948f84c-5386-11e8-88a6-c416b0889a51.png)

**Comment by patrykadas** [comment]
After @michalwarda feedback:
![flow 2x](https://user-images.githubusercontent.com/6234032/39881679-ec1ff6f6-5481-11e8-8a98-c63b41b4729f.png)

**Comment by michalwarda** [comment]
Done
