### ISSUE TITLE
Mainnet Alerts

### ISSUE THREAD

**Issue by patrykadas** [Userfeeds/cryptopurr#4]
[assets.zip](https://github.com/Userfeeds/cryptopurr/files/1889612/assets.zip)
Let's inform the user that it's better and cheaper to purr on one of the test nets. 

![mainnetalerts](https://user-images.githubusercontent.com/6234032/38495104-b652b866-3bf8-11e8-8683-21a2d1b78578.png)

https://projects.invisionapp.com/project/13791073

**Comment by michalwarda** [comment]
I've implemented a slightly different approach that is not like on design. It's just a warning on top of the page. We think that it is a simple solution and informs the user about the fact that he can switch network effectively.

**Comment by patrykadas** [comment]
![mobile-warning](https://user-images.githubusercontent.com/6234032/39243516-fc124e92-488d-11e8-8816-ab7f3ac80e81.png)
<img width="1680" alt="screen shot 2018-04-25 at 13 37 30" src="https://user-images.githubusercontent.com/6234032/39243519-00ad3160-488e-11e8-9dac-631a954347c0.png">

**Comment by michalwarda** [comment]
Done!
