### ISSUE TITLE
Performance improvements 

### ISSUE THREAD

**Issue by gkapkowski** [Userfeeds/cryptopurr#54]
Check what takes the most time in loading feed

**Comment by michalwarda** [comment]
I suggest adding http 2 as the first step on caching layer @gkapkowski. After that add pagination to feed @OrdonTeam can you post here an example request to the API that handles pagination?

**Comment by OrdonTeam** [comment]
https://api.userfeeds.io/ranking/cryptopurr_feed;context=ethereum:0x06012c8cf97bead5deae237070f9587f8e7a266d:307583;until=1527846793000;since=1527501193000

**Comment by michalwarda** [comment]
Done!
