### ISSUE TITLE
Links to external sites

### ISSUE THREAD

**Issue by patrykadas** [Userfeeds/cryptopurr#9]
I'm honestly not sure which solution's the best here.

1. Footer in the header section of 'adding new purr'
![1](https://user-images.githubusercontent.com/6234032/38556007-73408712-3cc8-11e8-9737-b90d2b27922c.png)

2. Include everything within header
![2](https://user-images.githubusercontent.com/6234032/38556008-735cc936-3cc8-11e8-98e9-3bc160225b1b.png)

3. Fixed bottom-right 
![3](https://user-images.githubusercontent.com/6234032/38556009-737f50c8-3cc8-11e8-9472-939908e7ebb0.png)

**Comment by michalwarda** [comment]
I didn't add the FAQ link because it is not implemented yet. Also I didn't put the fork it on Github because of the fact it's already inside Header.

**Comment by michalwarda** [comment]
@patrykadas please check it.

**Comment by michalwarda** [comment]
We should finish this one when #2 is done

**Comment by michalwarda** [comment]
Fix background to not be transparent

**Comment by michalwarda** [comment]
Change links to be also violet

**Comment by michalwarda** [comment]
Done!
